model:
  path: "dccuchile/bert-base-spanish-wwm-cased"
  name: "c_prof_w"
  lr: 2.717e-05
  batch: 32
  epochs: 3
  decay: 4.770e-3
  GA: 4
  hd: 0.098 #Not used
  ad: 0.123 #Not used
  eval_steps: 500
  save: "../models"
  checkpoints: "../checkpoints"

seed: 33
eval_pct: 0.2
label: 
  n_classes: 3
  task: "profession2label" #ideology2label,profession2label,label2ideology,label2profession
  target: "profession" #profession,ideology_binary,ideology_multiclass

text: "tweet" #tweet,Mtweet

lora:  
  r: 8
  alpha: 16
  dropout: 0.1
  target: ["query","key","value"]
  use: False

paths:
  labels: "../../encodings.pkl"
  data: "../../data/joined_back_para_syn.csv"
  logs: "../logs"

tokenized: False

tokenizer: 
  tokens: 
    - "[POLITICIAN]"
    - "[HASHTAG]"
    - "[POLITICAL_PARTY]"
    - "@user"
  save: "../tokenizers"
  path: "../tokenizers"
  data: "../tokenized/"
